Repository JeungHoSub/hanghae_node3week, pull requests merged in 2022-08, with the labels that each got.

#4 PR : 문서 최산화 dev/unchaptered > submain
  README.md
  docs/README.md
  docs/api/README.md
  docs/api/article.md
  docs/api/comment.md
  docs/api/user.md
  docs/env/README.md
  docs/git/Git-문법.md
  docs/git/Git-전략.md
  docs/git/Git-커밋규칙.md
  docs/git/README.md
  docs/sql/README.md
  docs/sql/default.sql
  src/layers/controllers/user.controller.js
  test.js
Labels: documentation

#5 PR : Article Router / Controller / Service / Repository 업로드
  docs/README.md
  src/index.js
  src/layers/controllers/article.controller.js
  src/layers/repositories/article.repository.js
  src/layers/routers/article.router.js
  src/layers/services/article.service.js
Labels: add

#6 PR : comment controller, service, router, repository
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/commnet.router.js
  src/layers/services/commnet.service.js
Labels: add

#8 PR : Auth Controller 매개변수 추출 부분에 joi 적용
  README.md
  docs/README.md
  docs/name/README.md
  src/layers/controllers/article.controller.js
  src/layers/routers/article.router.js
Labels: add

#11 PR : Article 좋아요 연결
  src/layers/controllers/article.controller.js
  src/layers/routers/article.router.js
  test2.js
Labels: add

#12 PR : Fix `**.js`, 임포트 에러 수정
  src/index.js
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/routers/comment.router.js
Labels: bug

#14 PR : API 명세서 수정
  docs/api/README.md
Labels: documentation

#15 PR: Comment 좋아요 연결
  src/layers/controllers/comment.controller.js
  src/layers/routers/comment.router.js
Labels: add

#16 PR: 게시글 및 댓글 좋아요 body/params 요청 추가
  src/layers/controllers/article.controller.js
  src/layers/controllers/comment.controller.js
Labels: add

#17 conflict solve comment.controller.js, comment.router.js
  src/layers/controllers/comment.controller.js
  src/layers/routers/comment.router.js
Labels: add

#19 PR : Join 기능 구현
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
Labels: add

#21 PR : login 기능 토큰과 암호화 없이 일단 구현
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
  tes.js
Labels: add

#23 PR : update comment (service | reporitory)
  src/layers/repositories/comment.repository.js
  src/layers/services/article.service.js
Labels: add

#25 PR: 게시글 좋아요 controller, service, repo 추가 및 수정
  docs/api/README.md
Labels: add

#28 PR : update comment(repository | service | controller)
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/services/article.service.js
  src/layers/services/comment.service.js
Labels: add

#29 PR : article 도메인 구현 완료
  docs/api/README.md
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/article.repository.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/services/article.service.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
Labels: enhancement, add

#30 PR : `/auth` 경로 구현 완료
  src/layers/controllers/article.controller.js
  src/layers/repositories/article.repository.js
  src/layers/services/article.service.js
Labels: enhancement, add

#31 PR : ✅JWT 구현 완료. 로그인과 글 작성으로 테스트 완료.
  package-lock.json
  package.json
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/article.router.js
  src/layers/services/auth.service.js
  src/modules/jwt.js
Labels: add

#33 PR : /auth 경로에 jwt middleware 반영 완료
  docs/api/README.md
  docs/request/article.json
  docs/request/like.json
  package-lock.json
  package.json
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/article.router.js
  src/layers/services/article.service.js
  src/layers/services/auth.service.js
  src/modules/jwt.js
Labels: enhancement, refactor

#34 PR : /auth 경로에 jwt middleware 반영 완료
  docs/api/README.md
  src/layers/controllers/article.controller.js
  src/layers/routers/article.router.js
Labels: enhancement, refactor

#35 PR : update comment(controller | service | repository).js / create comment.json (썬더클라이언트 파일)
  docs/request/comment.json
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/services/comment.service.js
Labels: add

#36 PR : 👏 jwt 관련 변수명 수정
  docs/request/auth.json
  src/layers/controllers/article.controller.js
  src/layers/routers/article.router.js
  src/layers/services/auth.service.js
  src/modules/jwt.js
Labels: refactor

#37 PR : 댓글 좋아요 && 게시물 좋아요 jwt 추가해서 수정
  src/layers/controllers/article.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/routers/article.router.js
  src/layers/routers/comment.router.js
Labels: enhancement, add

#40 PR : update comment(service | controller | repository) , comment api(Read.me)
  docs/api/README.md
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/comment.router.js
  src/layers/services/comment.service.js
Labels: bug, enhancement, add

#41 PR : add bcrypt
  docs/request/auth.json
  docs/request/comment.json
  package-lock.json
  package.json
  src/layers/controllers/article.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/article.router.js
  src/layers/routers/comment.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/modules/bcrypt.js
  src/modules/jwt.js
Labels: add

#43 PR : 작업 완료 (배포본)
  Logic.png
  README.md
  docs/README.md
  docs/api/README.md
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/comment.router.js
  src/layers/services/comment.service.js
  src/modules/jwt.js
Labels: documentation, enhancement, add

#44 PR : Prettier 적용 `module/prettier-eslint` > `submain
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc.js
  README.md
  package-lock.json
  package.json
  src/db.js
  src/env.js
  src/index.js
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/article.repository.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/article.router.js
  src/layers/routers/auth.router.js
  src/layers/routers/comment.router.js
  src/layers/services/article.service.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/modules/bcrypt.js
  src/modules/jwt.js
Labels: enhancement

#46 PR: article 관련 class complete
  src/layers/controllers/article.controller.js
  src/layers/repositories/article.repository.js
  src/layers/repositories/auth.repository.js
  src/layers/routers/article.router.js
  src/layers/services/article.service.js
  src/modules/jwt.js
Labels: enhancement

#48 PR : `env.js` 및 `db.js` 리팩토링 진행
  .gitignore
  package-lock.json
  package.json
  src/index.js
  src/models/_.loader.js
  src/models/env/env.js
  src/models/iterator/class.iterator.js
  src/modules/_.loader.js
  src/modules/providers/db.providers.js
  src/modules/providers/env.provider.js
  src/modules/providers/env.switcher.js
Labels: enhancement

#47 PR : 👏 Modify comment files, bcrypt.js, jwt.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/routers/comment.router.js
  src/layers/services/comment.service.js
  src/modules/bcrypt.js
  src/modules/jwt.js
Labels: enhancement

#49 PR : Layered Architecture 를 클래스로 개선
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc.js
  package-lock.json
  package.json
  src/db.js
  src/env.js
  src/index.js
  src/layers/controllers/article.controller.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/sample.controller.js
  src/layers/repositories/article.repository.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/sample.repository.js
  src/layers/routers/article.router.js
  src/layers/routers/auth.router.js
  src/layers/routers/comment.router.js
  src/layers/routers/sample.router.js
  src/layers/services/article.service.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/sample.service.js
  src/models/_.loader.js
  src/models/env/env.js
  src/models/iterator/class.iterator.js
  src/modules/_.loader.js
  src/modules/bcrypt.js
  src/modules/jwt.js
  src/modules/providers/db.providers.js
  src/modules/providers/env.provider.js
  src/modules/providers/env.switcher.js
Labels: enhancement
